/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package escritorio;

import javax.swing.JSlider;
import javax.swing.JTextField;

/**
 *
 * @author sergio
 */
public class NuevoUsuario extends javax.swing.JPanel {

    /**
     * Creates new form NuevoUsuario
     */
    
    private VentanaPrincipal parent;
    
    public NuevoUsuario() {
        initComponents();
    }
    
    public void setParent(VentanaPrincipal p) {
        parent = p;
    }

    public boolean isjRadioButtonHSelected() {
        return jRadioButtonH.isSelected();
    }

    public JSlider getjSliderBalonmano() {
        return jSliderBalonmano;
    }

    public JSlider getjSliderBasket() {
        return jSliderBasket;
    }

    public JSlider getjSliderFutbol() {
        return jSliderFutbol;
    }

    public JSlider getjSliderPadel() {
        return jSliderPadel;
    }

    public JTextField getApellidos() {
        return jTextFieldApellidos;
    }

    public JTextField getCorreo() {
        return jTextFieldCorreo;
    }

    public JTextField getNombre() {
        return jTextFieldNombre;
    }

    public JTextField getPwd1() {
        return jTextFieldPwd1;
    }

    public JTextField getPwd2() {
        return jTextFieldPwd2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelInsertar = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApe = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabelCorr = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelPwd = new javax.swing.JLabel();
        jTextFieldPwd1 = new javax.swing.JTextField();
        jLabelPwd2 = new javax.swing.JLabel();
        jTextFieldPwd2 = new javax.swing.JTextField();
        jButtonNuevoUsuario = new javax.swing.JButton();
        jLabelSexo = new javax.swing.JLabel();
        jRadioButtonH = new javax.swing.JRadioButton();
        jRadioButtonM = new javax.swing.JRadioButton();
        Fútbol = new javax.swing.JLabel();
        jSliderFutbol = new javax.swing.JSlider();
        jLabelPadel = new javax.swing.JLabel();
        jSliderBalonmano = new javax.swing.JSlider();
        jSliderPadel = new javax.swing.JSlider();
        jLabelBasket = new javax.swing.JLabel();
        jSliderBasket = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();

        jLabelInsertar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelInsertar.setText("INSERTAR NUEVO USUARIO");

        jLabelNombre.setText("Nombre ");

        jLabelApe.setText("Apellidos");

        jLabelCorr.setText("Correo");

        jLabelPwd.setText("Contraseña");

        jLabelPwd2.setText("Repetir");

        jButtonNuevoUsuario.setText("Crear usuario");
        jButtonNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoUsuarioActionPerformed(evt);
            }
        });

        jLabelSexo.setText("Sexo");

        buttonGroup1.add(jRadioButtonH);
        jRadioButtonH.setText("Hombre");

        buttonGroup1.add(jRadioButtonM);
        jRadioButtonM.setText("Mujer");

        Fútbol.setText("Fútbol");

        jSliderFutbol.setMajorTickSpacing(1);
        jSliderFutbol.setMaximum(5);
        jSliderFutbol.setPaintLabels(true);
        jSliderFutbol.setPaintTicks(true);
        jSliderFutbol.setSnapToTicks(true);
        jSliderFutbol.setValue(0);

        jLabelPadel.setText("Padel");

        jSliderBalonmano.setMajorTickSpacing(1);
        jSliderBalonmano.setMaximum(5);
        jSliderBalonmano.setPaintLabels(true);
        jSliderBalonmano.setPaintTicks(true);
        jSliderBalonmano.setSnapToTicks(true);
        jSliderBalonmano.setValue(0);

        jSliderPadel.setMajorTickSpacing(1);
        jSliderPadel.setMaximum(5);
        jSliderPadel.setPaintLabels(true);
        jSliderPadel.setPaintTicks(true);
        jSliderPadel.setSnapToTicks(true);
        jSliderPadel.setValue(0);

        jLabelBasket.setText("Basket");

        jSliderBasket.setMajorTickSpacing(1);
        jSliderBasket.setMaximum(5);
        jSliderBasket.setPaintLabels(true);
        jSliderBasket.setPaintTicks(true);
        jSliderBasket.setSnapToTicks(true);
        jSliderBasket.setValue(0);

        jLabel1.setText("Balonmano");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCorr)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fútbol)
                            .addComponent(jLabelPadel)
                            .addComponent(jLabelBasket)
                            .addComponent(jLabel1))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderBalonmano, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jSliderFutbol, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jSliderPadel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jSliderBasket, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelApe)
                            .addComponent(jLabelPwd)
                            .addComponent(jLabelPwd2)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelSexo))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonM))
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(jTextFieldCorreo)
                            .addComponent(jTextFieldPwd1)
                            .addComponent(jTextFieldPwd2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(jTextFieldApellidos)))
                    .addComponent(jLabelInsertar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNuevoUsuario)
                        .addGap(11, 11, 11)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelInsertar)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApe)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCorr)
                    .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPwd)
                    .addComponent(jTextFieldPwd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPwd2)
                    .addComponent(jTextFieldPwd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSexo)
                    .addComponent(jRadioButtonH)
                    .addComponent(jRadioButtonM))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderFutbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fútbol))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPadel)
                    .addComponent(jSliderPadel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBasket)
                    .addComponent(jSliderBasket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderBalonmano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoUsuario)
                    .addComponent(jButtonCancelar))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoUsuarioActionPerformed
        // TODO add your handling code here:
        parent.crearUsuario();
    }//GEN-LAST:event_jButtonNuevoUsuarioActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        parent.cerrarCreacionUsuario();
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fútbol;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonNuevoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApe;
    private javax.swing.JLabel jLabelBasket;
    private javax.swing.JLabel jLabelCorr;
    private javax.swing.JLabel jLabelInsertar;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPadel;
    private javax.swing.JLabel jLabelPwd;
    private javax.swing.JLabel jLabelPwd2;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JRadioButton jRadioButtonH;
    private javax.swing.JRadioButton jRadioButtonM;
    private javax.swing.JSlider jSliderBalonmano;
    private javax.swing.JSlider jSliderBasket;
    private javax.swing.JSlider jSliderFutbol;
    private javax.swing.JSlider jSliderPadel;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPwd1;
    private javax.swing.JTextField jTextFieldPwd2;
    // End of variables declaration//GEN-END:variables
}
